sysdb:
  flags:
    version-file-enabled: true
    soft-delete-max-age: 1s
    soft-delete-cleanup-interval: 2s
    s3-endpoint: "http://minio:9000"
    s3-access-key-id: "minio"
    s3-secret-access-key: "minio123"
    s3-force-path-style: true
    create-bucket-if-not-exists: true
rustFrontendService:
  # We have to specify the command, because the Dockerfile uses the CLI since its shared with
  # single node, so in values.dev we pass the CONFIG_PATH into the chroma run command
  command: '["chroma", "run", "$(CONFIG_PATH)"]'
  otherEnvConfig: |
    - name: CHROMA_ALLOW_RESET
      value: "true"
    - name: RUST_BACKTRACE
      value: 'value: "1"'
    - name: CONFIG_PATH
      value: "tilt_config.yaml"

frontendService:
  otherEnvConfig: |
    - name: CHROMA_ALLOW_RESET
      value: "true"

queryService:
  env:
    - name: RUST_BACKTRACE
      value: 'value: "1"'
    - name: CONFIG_PATH
      value: 'value: "/tilt_config.yaml"'

compactionService:
  env:
    - name: RUST_BACKTRACE
      value: 'value: "1"'
    - name: CONFIG_PATH
      value: 'value: "/tilt_config.yaml"'

garbageCollector:
  configuration: |
    service_name: "garbage-collector"
    otel_endpoint: "http://otel-collector:4317"
    relative_cutoff_time_seconds: 60 # GC all versions created at time < now() - relative_cutoff_time_seconds (1 minute)
    max_collections_to_gc: 1000
    gc_interval_mins: 1
    disallow_collections: []
    tenant_mode_overrides:
      "default_tenant": "delete"
    sysdb_config:
      host: "sysdb.chroma"
      port: 50051
      connect_timeout_ms: 60000
      request_timeout_ms: 60000
    dispatcher_config:
      num_worker_threads: 4
      dispatcher_queue_size: 100
      worker_queue_size: 100
    storage_config:
      s3:
        bucket: "chroma-storage"
    assignment_policy:
      rendezvous_hashing:
        hasher: Murmur3
    my_member_id: "garbage-collector-0"
    memberlist_provider:
      custom_resource:
        kube_namespace: "chroma"
        memberlist_name: "garbage-collection-service-memberlist"
        queue_size: 100
