[project]
name = "code-search"
version = "0.1.0"
description = "A Github-inspired code search utility"
authors = [
    {name = "Kyle Diaz"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb (>=1.0.9,<2.0.0)",
    "sentence-transformers (>=4.1.0,<5.0.0)",
    "transformers (>=4.51.3,<5.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
