name: 📦 Release JavaScript client

on:
  push:
    tags:
      - 'js_release_[0-9]+\.[0-9]+\.[0-9]+'  # Match tags in the form js_release_X.Y.Z
      - 'js_release_alpha_[0-9]+\.[0-9]+\.[0-9]+'  # Match tags in the form js_release_alpha_X.Y.Z
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
env:
  PNPM_CACHE_FOLDER: .cache/pnpm
jobs:
  build-bindings:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
            build: cd rust/js_bindings && yarn build --target x86_64-apple-darwin
          - host: windows-latest
            build: cd rust/js_bindings && yarn build --target x86_64-pc-windows-msvc
            target: x86_64-pc-windows-msvc
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian
            build: cd rust/js_bindings && yarn build --target x86_64-unknown-linux-gnu
          - host: macos-latest
            target: aarch64-apple-darwin
            build: cd rust/js_bindings && yarn build --target aarch64-apple-darwin
          - host: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian-aarch64
            build: cd rust/js_bindings && yarn build --target aarch64-unknown-linux-gnu
          - host: windows-latest
            target: aarch64-pc-windows-msvc
            build: cd rust/js_bindings && yarn build --target aarch64-pc-windows-msvc

    name: Build binding - ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        if: ${{ !matrix.settings.docker }}
        with:
          node-version: 18
          cache: yarn

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        if: ${{ !matrix.settings.docker }}
        with:
          toolchain: stable
          targets: ${{ matrix.settings.target }}

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.settings.target }}-cargo-${{ matrix.settings.host }}

      - name: Install JS bindings dependencies
        run: cd rust/js_bindings && yarn install

      - name: Build in docker
        uses: addnab/docker-run-action@v3
        if: ${{ matrix.settings.docker }}
        with:
          image: ${{ matrix.settings.docker }}
          options: '--user 0:0 -v ${{ github.workspace }}:/build -w /build'
          run: ${{ matrix.settings.build }}

      - name: Build
        run: ${{ matrix.settings.build }}
        if: ${{ !matrix.settings.docker }}
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.settings.target }}
          path: rust/js_bindings/${{ env.APP_NAME }}.*.node
          if-no-files-found: error


  release:
    strategy:
      fail-fast: false
      matrix:
        registry: [ "https://registry.npmjs.org", "https://npm.pkg.github.com" ]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Resolve tag
      id: tag
      shell: bash
      run: |
        # If the workflow was triggered by a push on a tag, use github.ref_name.
        # If manually dispatched, use the tag value supplied in the workflow input.
        if [[ "${{ github.event_name }}" == "push" ]]; then
          echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        else
          echo "tag=${{ inputs.tag }}" >> $GITHUB_OUTPUT
        fi

    - name: Check if tag matches the pattern
      run: |
        if [[ "${{ steps.tag.outputs.tag }}" =~ ^js_release_alpha_[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Tag matches the pattern js_release_alpha_X.Y.Z"
          echo "NPM_SCRIPT=release_alpha" >> "$GITHUB_ENV"
        elif [[ "${{ steps.tag.outputs.tag }}" =~ ^js_release_[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Tag matches the pattern js_release_X.Y.Z"
          echo "NPM_SCRIPT=release" >> "$GITHUB_ENV"
        else
          echo "Tag does not match the release tag pattern, exiting workflow"
          exit 1
        fi
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
        run_install: false
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "18.x"
        registry-url: ${{ matrix.registry }}
        check-latest: false
        token: ${{ matrix.registry == 'https://registry.npmjs.org' && secrets.NPM_TOKEN || secrets.GITHUB_TOKEN }}
        cache: 'pnpm'
        cache-dependency-path: 'clients/js/pnpm-lock.yaml'
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      working-directory: ./clients/js/
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: rust/js_bindings
    - name: Build packages
      run: pnpm build
      working-directory: ./clients/js/
    - name: Update package.json with organization scope for GitHub packages
      if: matrix.registry == 'https://npm.pkg.github.com'
      run: |
        # Update chromadb package
        CHROMADB_PKG="./packages/chromadb/package.json"
        ORG_NAME="@chroma-core"
        PACKAGE_NAME=$(jq -r '.name' $CHROMADB_PKG)
        jq --arg org "$ORG_NAME" --arg name "$PACKAGE_NAME" '.name = "\($org)/\($name)"' $CHROMADB_PKG > tmp.$$.json && mv tmp.$$.json $CHROMADB_PKG

        # Update chromadb-client package
        CLIENT_PKG="./packages/chromadb-client/package.json"
        PACKAGE_NAME=$(jq -r '.name' $CLIENT_PKG)
        jq --arg org "$ORG_NAME" --arg name "$PACKAGE_NAME" '.name = "\($org)/\($name)"' $CLIENT_PKG > tmp.$$.json && mv tmp.$$.json $CLIENT_PKG
      working-directory: ./clients/js/
    - name: Publish packages
      run: pnpm publish -r --access public --no-git-checks
      working-directory: ./clients/js/
      env:
        NODE_AUTH_TOKEN: ${{ matrix.registry == 'https://registry.npmjs.org' && secrets.NPM_TOKEN || secrets.GITHUB_TOKEN }}
